<?php

/*
 * implement  hook_init
 */

function duhoc_student_init() {
  if(isset($_POST['ajax_html_ids']))
    unset($_POST['ajax_html_ids']);
}

/**
 * implement hook menu
 */
function duhoc_student_menu() {
  $items['hocvien/%'] = array(
    'title' => 'Step 1',
    'page callback' => 'duhoc_student_admin',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['hocvien/%/info'] = array(
    'title' => 'Step 1',
    'page callback' => 'duhoc_student_admin',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['hocvien/%/pathway'] = array(
    'title' => 'Step 2',
    'page callback' => 'duhoc_student_admin',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['hocvien/%/add2'] = array(
    'title' => 'Step 3',
    'page callback' => 'duhoc_student_admin',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%/hocvien'] = array(
    'title' => 'Chỉnh sửa',
    'page callback' => 'drupal_goto',
    'page arguments' => array('hocvien/%'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function duhoc_student_admin($id) {
  module_load_include('inc', 'node', 'node.pages');
  $node = node_load($id);
  $form = node_page_edit($node);
 // $form = '<div class="clear-form goldprice-sxht">' . $form . '</div>';
  return $form;
}
/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 * Implement hook_theme
 */
function duhoc_student_theme($existing, $type, $theme, $path) {
  return array(
    'country_node_form' => array(
      'render element' => 'form',
      'path' => drupal_get_path('module', 'duhoc_student').'/templates',
      'template' => 'country'
    ),
    'course_node_form' => array(
      'render element' => 'form',
      'path' => drupal_get_path('module', 'duhoc_student').'/templates',
      'template' => 'course'
    ),
    'contract_node_form' => array(
      'render element' => 'form',
      'path' => drupal_get_path('module', 'duhoc_student').'/templates',
      'template' => 'contract'
    ),
  );
}

/**
 * im plement hook_form_alter
 */
function duhoc_student_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'course_node_form') {
    if(!isset($form_state['build_info']['files'])){
      $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
    }
  }
  if($form_id == 'country_node_form') {
    if(!isset($form_state['build_info']['files'])){
      $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
    }
      $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit Your Tip'),
        '#submit' => array('node_form_submit'),
        '#ajax' => array(
          'wrapper' => str_replace('_','-',$form['#form_id']),
          'callback' => 'simone_forms_ajax_callback',
          'method' => 'replace',
          'effect' => 'fade'
        ),
      );

  }
  $form['options']['name']['views.php']['#title'] = 'Trường tính toán';
  $form['options']['name']['views.php']['#description'] = '';
  $form['options']['name']['views.php']['#prefix'] = '<div class="user_show">';
  $form['options']['name']['views.php']['#suffix'] = '</div>';
  $form['options']['name']['#prefix'] = '<div class="user_hide">';
  $form['options']['name']['#suffix'] = '</div>';
   if($form_id == 'views_ui_config_item_form3') {
     $form['options']['#prefix'] = '<div class="php_show">';
     $form['options']['#suffix'] = '</div>';
     $form['#submit'][]  = 'duhoc_student_add';
   }
}
function simone_forms_ajax_callback(&$form, &$form_state) {

  if(form_get_errors()){
    return $form;
  }
  else{
    return $form;
  }
}
function duhoc_student_add() {
  drupal_set_message('xin chao');
}

function duhoc_student_node_add () {
  module_load_include('inc', 'node', 'node.pages');
  $form = node_add('country');
  return drupal_render($form);
}
