<?php

/*
 * implement  hook_init
 */

function duhoc_student_init() {
  if(isset($_POST['ajax_html_ids']))
    unset($_POST['ajax_html_ids']);
}


function duhoc_student_admin($id='') {

    module_load_include('inc', 'node', 'node.pages');
    $node = node_load($id);
    $form = node_page_edit($node);
   // $form = '<div class="clear-form goldprice-sxht">' . $form . '</div>';
    return $form;


}
/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 * Implement hook_theme
 */
function duhoc_student_theme($existing, $type, $theme, $path) {
  return array(
    'country_node_form' => array(
      'render element' => 'element',
    ),
    'course_node_form' => array(
      'render element' => 'form',
      'path' => drupal_get_path('module', 'duhoc_student').'/templates',
      'template' => 'course'
    ),
    'contract_node_form' => array(
      'render element' => 'form',
      'path' => drupal_get_path('module', 'duhoc_student').'/templates',
      'template' => 'contract'
    ),
  );
}
function theme_country_node_form($form) {


}

/**
 * im plement hook_form_alter
 */
function duhoc_student_form_alter(&$form, &$form_state, $form_id) {

 if($form_id =='hocvien_node_form') {
   if(!isset($form_state['build_info']['files'])){
     $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
   }
   if(arg(3) == 'basic') {
     $form['field_student_pathway']['#access'] = false;
     $form['field_student_visa']['#access'] = false;
     $form['field_student_contract']['#access'] = false;
   }
   if(arg(3) == 'pathway') {
     $form['field_student_basic']['#access'] = false;
     $form['field_student_visa']['#access'] = false;
     $form['field_student_contract']['#access'] = false;
   }
   if(arg(3) == 'contract') {
     $form['field_student_basic']['#access'] = false;
     $form['field_student_visa']['#access'] = false;
     $form['field_student_pathway']['#access'] = false;
   }
   if(arg(3) == 'visa') {
     $form['field_student_basic']['#access'] = false;
     $form['field_student_contract']['#access'] = false;
     $form['field_student_pathway']['#access'] = false;
   }
 }

  if($form_id == 'contract_node_form') {

  }
  if($form_id == 'course_node_form') {
    if(!isset($form_state['build_info']['files'])){
      $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
    }
  }
  if($form_id == 'country_node_form') {



    $form['field_country']['#access'] = false;
    if(!isset($form_state['build_info']['files'])){
      $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
    }
      $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit Your Tip'),
        '#submit' => array('node_form_submit'),
        '#ajax' => array(
          'wrapper' => str_replace('_','-',$form['#form_id']),
          'callback' => 'simone_forms_ajax_callback',
          'method' => 'replace',
          'effect' => 'fade'
        ),
      );
  }

}
function simone_forms_ajax_callback(&$form, &$form_state) {

  if(form_get_errors()){
    return $form;
  }
  else{
    return $form;
  }
}
function duhoc_student_add() {
  drupal_set_message('xin chao');
}

function duhoc_student_node_add () {
  module_load_include('inc', 'node', 'node.pages');
  $form = node_add('country');
  return drupal_render($form);
}
