<?php

/*
 * implement hook_menu
 */
function duhoc_report_menu() {
  $items = array();
  $items['add/operator'] = array(
    'title' => 'Add field',
    'page callback' => 'duhoc_report_add_operator',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function duhoc_report_add_operator() {
  $view = views_get_view('new_views');
  $view->set_display('default');
  $op = $view -> display['default'];
  $name = $op ->display_options['fields']['php']['label'] ;
  $op ->display_options['fields']['php']['label'] = $name .'ten cua ban';
  $view->set_items_per_page(4);
  $view->pre_execute();
  $view->execute();
  return $view->render();
}


function duhoc_report_views_pre_execute(&$view) {

}

function duhoc_report_form_alter(&$form, &$form_state, $form_id) {


}

function duhoc_report_export_to_excel($content) {
  header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
  header("Content-Disposition: attachment; filename=Report_".arg(2).".xls");  //File name extension was wrong
  header("Expires: 0");
  header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
  header("Cache-Control: private",false);
  echo $content;
  exit;
}

/**
 * implement hook block_info
 */

function duhoc_report_block_info() {
  $blocks['Commist'] = array(
    'info' => t(''),
  );
  return $blocks;
}

/**
 * implement hook_block_view
 */

function duhoc_report_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'menu_report':
      $block['content'] = duhoc_report_menu_left();
      break;
  }
  return $block;
}


function duhoc_report_commission_received() {
  global $user;
  if(!isset($user->roles[8])) {
    $query = db_query("SELECT ");
  }
  $query = db_query("SELECT SUM(com.field_com_received_contract_curr_value) FROM field_data_field_com_received_contract_curr as com INNER JOIN field_data_field_collection_test as path ON com.entity_id = path.field_collection_test_value WHERE path.entity_id =:eid",array(':eid' =>1))->fetchField();
}

function duhoc_report_type() {
  $type = arg(2);
  $output = '';
  if(!isset($type)) {
    $output .= '<h2>Commission Due Report</h2>';
  }
  else {
    if($type =='due')
      $output .= '<h2>Commission Due Report</h2>';
    if($type =='pending')
      $output .= '<h2>Commission Pendding Report</h2>';
    if($type == 'revenue')
      $output .= '<h2>Monthly Revenue Reports</h2>';
  }
  return $output;
 }

