<?php

/*
 * implement hook_menu
 */
function duhoc_report_menu() {
  $items = array();
  $items['add/operator'] = array(
    'title' => 'Add field',
    'page callback' => 'duhoc_report_add_operator',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['snippet/addmore'] = array(
    'title' => t('Example form'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_form'),
    'access callback' => TRUE,
  );
  return $items;
}

function duhoc_report_add_operator() {
  $view = views_get_view('new_views');
  $view->set_display('default');
  $op = $view -> display['default'];
  $name = $op ->display_options['fields']['php']['label'] ;
  $op ->display_options['fields']['php']['label'] = $name .'ten cua ban';
  $view->set_items_per_page(4);
  $view->pre_execute();
  $view->execute();
  return $view->render();
}


function duhoc_report_views_pre_execute(&$view) {
}

function duhoc_report_form_alter(&$form, &$form_state, $form_id) {

  if ($form['#id'] =='views-exposed-form-view-dynamic-page-1'){
     $form['submit']['#prefix'] = '<div class="add_them"><input type="button" onclick="clickME()" value="Add more" id="edit-toantua"></div>';
      $form['name-report'] = array(
        '#type' => 'textfield',
        '#zise' => -2,
        '#title' => t('Report Name: '),
        '#weight' => -1
      );
    $form['file'] = array(
      '#type' => 'fieldset',
      '#title' => t('Operator'),
      '#prefix' => '<div id="admin_vanri">',
      '#suffix' => '</div>',
      '#weight' => 0
    );
    for($i = 0;$i<=5;$i++) {
      $form['file']['tieude_'.$i] = array(
        '#type' => 'textfield',
        '#size' => 22,
        '#title' => t('Label: '),
        '#prefix' => '<div class="more_form" id="admin_vanri'.$i.'">',
      );
      $form['file']['toantu_'.$i] = array(
        '#type' => 'textfield',
        '#size' => 25,
        '#title' => t('Operator: '),
        '#suffix' => '</div>',
      );
    }

  }
}

function myform_selectors_cancel_submit($form,&$form_state) {
  $form_state['rebuild']= false;
}

function admin_callback($form,&$form_state) {
  return '123';
}

function duhoc_report_export_to_excel($content) {
  header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
  header("Content-Disposition: attachment; filename=Report_".arg(2).".xls");  //File name extension was wrong
  header("Expires: 0");
  header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
  header("Cache-Control: private",false);
  echo $content;
  exit;
}

/**
 * implement hook block_info
 */

function duhoc_report_block_info() {
  $blocks['Commist'] = array(
    'info' => t(''),
  );
  return $blocks;
}

/**
 * implement hook_block_view
 */

function duhoc_report_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'menu_report':
      $block['content'] = duhoc_report_menu_left();
      break;
  }
  return $block;
}

function duhoc_report_commission_received() {
  global $user;
  if(!isset($user->roles[8])) {
    $query = db_query("SELECT ");
  }
  $query = db_query("SELECT SUM(com.field_com_received_contract_curr_value) FROM field_data_field_com_received_contract_curr as com INNER JOIN field_data_field_collection_test as path ON com.entity_id = path.field_collection_test_value WHERE path.entity_id =:eid",array(':eid' =>1))->fetchField();
}

function duhoc_report_type() {
  $type = arg(2);
  $output = '';
  if(!isset($type)) {
    $output .= '<h2>Commission Due Report</h2>';
  }
  else {
    if($type =='due')
      $output .= '<h2>Commission Due Report</h2>';
    if($type =='pending')
      $output .= '<h2>Commission Pendding Report</h2>';
    if($type == 'revenue')
      $output .= '<h2>Monthly Revenue Reports</h2>';
  }
  return $output;
 }

