<?php

/**
 * implement hook_init
 */

function duhoc_chart_init() {
  drupal_add_js(drupal_get_path('module','duhoc_chart').'/misc/jsapi');
}

/**
 * implement hook block_info
 */

function duhoc_chart_block_info() {
  $blocks['chart_colum_home'] = array(
    'info' => t('Chart colum home'),
  );
  $blocks['chart_colum_home_office'] = array(
    'info' => t('Chart colum home Office'),
  );
  return $blocks;
}

/**
 * implement hook_block_view
 */

function duhoc_chart_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'chart_colum_home':
      $block['content'] = duhoc_chart_colum();
      break;
    case 'chart_colum_home_office':
      $block['content'] = duhoc_chart_colum_office();
      break;
  }
  return $block;
}

function duhoc_chart_colum() {
  $timenow = time();
  $ynow = date('Y',$timenow);
  $mnow = date('m',$timenow);

  $js = '
      google.load("visualization", "1", {packages:["corechart"]});
google.setOnLoadCallback(drawChart);
function drawChart() {

  var data = google.visualization.arrayToDataTable([
    ["Month", "Now year", "Tagets"],
   '.duhoc_chart_data().'
  ]);
  var options = {
    chartArea:{left:0,top:60,width:"88%"},
    hAxis: {title: "", titleTextStyle: {color: "red"}}
  };

  var chart = new google.visualization.ColumnChart(document.getElementById("chart_div"));

  chart.draw(data, options);


}
  ';
  drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
  $header = array('Month','Sales');
  $output = '<h2>Monthly Sales</h2>';
  $output .= '<div class="content_home"> <div id="chart_div" style="width:700px;height:400px;float:left"></div>';

  $output  .= '<div class="content_mont" style ="width:200px;float:right;"><h2>Table Mothly Sales</h2>'.theme('table', array('header' => $header,   'rows' => duhoc_chart_time_now() )).'</div>';
  $output .= '</div>';
  return $output;
}
function duhoc_chart_data() {
  global $user;
  $data ='';
  for($i = 1 ; $i <= 12; $i ++) {
    $taget = duhoc_chart_tagets($user->uid,$i);
    if(!isset($taget))
      $taget = 0;
    $data .= '["'.duhhoc_chart_convert_month($i).'",      '.duhoc_chart_sum_contract($i).',      '.$taget.'], ' ;
  }
  return $data;
}

function duhoc_chart_tagets($uid,$moth) {
  $query = db_query("SELECT target.field_target_value FROM field_data_field_target as target INNER JOIN field_data_field_th_ng as mont ON
target.delta = mont.delta WHERE FROM_UNIXTIME(mont.field_th_ng_value,'%c') = :month AND mont.entity_id = :uid",array(':month' => $moth,':uid' => $uid));
  foreach ($query as $record) {
    $result =  $record ->field_target_value;
  }
return $result;
}

function duhoc_chart_time_now() {
  //$ymonth = date('m',time());
  $ymonth = '12';
for($i = 1; $i <= $ymonth ;$i++) {
  $sale = duhoc_chart_sum_contract($i);
  $row['month'] = duhhoc_chart_convert_month($i);
  $row['sale'] = $sale;
  $rows[] = $row;
}

  return $rows;
}

function duhoc_chart_sum_contract($month) {
  $query = db_query("SELECT contract.field_student_contract_value FROM field_data_field_student_contract as contract INNER JOIN node as n ON contract.entity_id = n.nid WHERE FROM_UNIXTIME(n.created,'%c') = :month",array(':month' => $month))->rowCount();
  return $query;
}
function duhhoc_chart_convert_month($month) {
  switch($month) {
    case '1':
      return 'January';
    break;
    case '2':
      return 'February';
    break;
    case '3':
      return 'March';
    break;
    case '4':
      return 'April';
    break;
    case '5':
      return 'May';
    break;
    case '6':
      return 'June';
    break;
    case '7':
      return 'July';
    break;
    case '8':
      return 'August';
    break;
    case '9':
      return 'September';
    break;
    case '10':
      return 'October';
    break;
    case '11':
      return 'November';
    break ;
    case '12':
      return 'December';
    break;
  }
}

function duhoc_chart_form_select() {
  $form = array();
  $form['selected'] = array(
    '#type' => 'select',
    '#title' => t('Selected'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
  );
}

function duhoc_chart_user_roles($role) {
  $query = db_query("SELECT uid FROM {users_roles} WHERE rid = :role",array(':role' => $role));
  $count = $query->rowCount();
  $i = 0;
  $data = '';
  foreach($query as $result) {
    $i++;
    if($i == $count - 1)
      $data .= $result -> uid;
    else
      $data = $result -> uid.', ';
  }
  return $data;
}