<?php

/**
 * implement hook_init
 */

function duhoc_chart_init() {
  drupal_add_js(drupal_get_path('module','duhoc_chart').'/misc/jsapi');
}

/**
 * implement hook block_info
 */

function duhoc_chart_block_info() {
  $blocks['chart_colum_home'] = array(
    'info' => t('Chart colum home'),
  );
  $blocks['chart_colum_home_office'] = array(
    'info' => t('Chart colum home Office'),
  );
  return $blocks;
}

/**
 * implement hook_block_view
 */

function duhoc_chart_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'chart_colum_home':
      $block['content'] = duhoc_chart_colum();
      break;
  }
  return $block;
}

function duhoc_chart_colum() {
  $js = '
      google.load("visualization", "1", {packages:["corechart"]});
google.setOnLoadCallback(drawChart);
function drawChart() {

  var data = google.visualization.arrayToDataTable([
    ["Month", "Now year", "Tagets"],
   '.duhoc_chart_data().'
  ]);
    var data2 = google.visualization.arrayToDataTable([
    ["Month", "Now year", "Tagets"],
   '.duhoc_chart_data_office().'
  ]);
  var options = {
    chartArea:{left:20,top:60,width:"86%"},
    hAxis: {title: "", titleTextStyle: {color: "red"}}
  };

  var chart = new google.visualization.ColumnChart(document.getElementById("chart_div"));
  chart.draw(data, options);

  var chart2 = new google.visualization.ColumnChart(document.getElementById("chart_div2"));
  chart2.draw(data2, options);

}
  ';
  drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
  $header = array('Month','Sales');
  $output = '<h2>Monthly Sales</h2>'.drupal_render(drupal_get_form('duhoc_chart_form_select'));
  $output .= '<div class="content_home"> <div id="chart_div" style="width:700px;height:400px;float:left"></div>';
  $output  .= '<div class="content_mont" style ="width:200px;float:right;"><h2>Table Mothly Sales</h2>'.theme('table', array('header' => $header,   'rows' => duhoc_chart_time_now() )).'</div>';
  $output .= '</div>';
  $output .= '<div class="clearfix"></div>';
  $output .= '<h2>Monthly Sales Office</h2>';
  $output .= '<div class="content_home1"> <div id="chart_div2" style="width:700px;height:400px;float:left"></div>';
  $output  .= '<div class="content_mont" style ="width:200px;float:right;"><h2>Table Mothly Sales</h2>'.theme('table', array('header' => $header,   'rows' => duhoc_chart_time_now_office() )).'</div>';
  $output .= '</div>';
  return $output;
}
function duhoc_chart_data() {
  global $user;
  $data ='';
  for($i = 1 ; $i <= 12; $i ++) {
    $taget = duhoc_chart_tagets($user->uid,$i);
    if(!isset($taget))
      $taget = 0;
    $data .= '["'.duhhoc_chart_convert_month($i).'",      '.duhoc_chart_sum_contract($i,$user->uid).',      '.$taget.'], ' ;
  }
  return $data;
}

function duhoc_chart_data_office() {
  $data ='';
  for($i = 1 ; $i <= 12; $i ++) {
    $taget = duhoc_chart_tagets_office($i);
    if(!isset($taget))
      $taget = 0;
    $data .= '["'.duhhoc_chart_convert_month($i).'",      '.duhoc_chart_sum_contract_office($i).',      '.$taget.'], ' ;
  }
  return $data;
}
function duhoc_chart_tagets($uid,$moth) {
  $query = db_query("SELECT target.field_target_value as giatri FROM field_data_field_target as target INNER JOIN field_data_field_th_ng as mont ON
target.delta = mont.delta WHERE FROM_UNIXTIME(mont.field_th_ng_value,'%c') = :month AND mont.entity_id = :uid",array(':month' => $moth,':uid' => $uid));
  foreach ($query as $record) {
    $result =  $record ->giatri;
  }

return $result;
}

function duhoc_chart_tagets_office($moth) {
  $uid = duhoc_chart_list_member();
  $query = db_query("SELECT SUM(target.field_target_value) as giatri FROM field_data_field_target as target INNER JOIN field_data_field_th_ng as mont ON
target.delta = mont.delta WHERE FROM_UNIXTIME(mont.field_th_ng_value,'%c') = :month AND mont.entity_id IN (:uid)",array(':month' => $moth,':uid' => $uid));
  foreach ($query as $record) {

    $result =  $record ->giatri;
  }
  return $result;
}
function duhoc_chart_time_now_office() {
  global $user;
  //$ymonth = date('m',time());
  $ymonth = '12';
  for($i = 1; $i <= $ymonth ;$i++) {
    $sale = duhoc_chart_sum_contract($i,$user ->uid);
    $row['month'] = duhhoc_chart_convert_month($i);
    $row['sale'] = $sale;
    $rows[] = $row;
  }
  return $rows;
}

function duhoc_chart_time_now() {
  global $user;
  //$ymonth = date('m',time());
  $ymonth = '12';
for($i = 1; $i <= $ymonth ;$i++) {
  $sale = duhoc_chart_sum_contract($i,$user ->uid);
  $row['month'] = duhhoc_chart_convert_month($i);
  $row['sale'] = $sale;
  $rows[] = $row;
}
  return $rows;
}

function duhoc_chart_sum_contract($month,$uid) {
  $query = db_query("SELECT contract.field_student_contract_value FROM
  field_data_field_student_contract as contract
   INNER JOIN   field_data_field_create_date as creat ON contract.field_student_contract_value =  creat.entity_id
   INNER JOIN  node as n ON  contract.entity_id = n.nid
  WHERE n.uid = :uid AND FROM_UNIXTIME(creat.field_create_date_value,'%c') = :month",array(':uid' => $uid,':month' => $month))->rowCount();
  return $query;
}

function duhoc_chart_sum_contract_office($month) {
  $list_uid = duhoc_chart_list_uid(8);
  $query = db_query("SELECT contract.field_student_contract_value FROM
  field_data_field_student_contract as contract
   INNER JOIN   field_data_field_create_date as creat ON contract.field_student_contract_value =  creat.entity_id
   INNER JOIN  node as n ON  contract.entity_id = n.nid
  WHERE n.uid IN (:uid) AND FROM_UNIXTIME(creat.field_create_date_value,'%c') = :month",array(':uid' => $list_uid,':month' => $month))->rowCount();
  return $query;
}

function duhoc_chart_list_uid ($role = null) {
  global $user;

  if(isset($user->roles[8])) {
    $query = db_query("SELECT uid FROM users_roles WHERE rid = :rid", array(':rid' => $role));
    foreach($query as $result) {
      $row[] = $result -> uid;
    }
    $str = implode (", ", $row);
  }
  else
    $str = $user -> uid;
  return $str;
}

function duhoc_chart_list_member() {
  global $user;
  $user = user_load($user ->uid);
  $area = $user ->field_area['und'][0]['value'];
  $query = db_query("SELECT entity_id FROM {field_data_field_area} WHERE field_area_value = :area" , array(':area' => $area));

  foreach($query as $result) {
    $row[] = $result -> entity_id;
  }

  $str = implode (", ", $row);
  return $str;
}

function duhhoc_chart_convert_month($month) {
  switch($month) {
    case '1':
      return 'January';
    break;
    case '2':
      return 'February';
    break;
    case '3':
      return 'March';
    break;
    case '4':
      return 'April';
    break;
    case '5':
      return 'May';
    break;
    case '6':
      return 'June';
    break;
    case '7':
      return 'July';
    break;
    case '8':
      return 'August';
    break;
    case '9':
      return 'September';
    break;
    case '10':
      return 'October';
    break;
    case '11':
      return 'November';
    break ;
    case '12':
      return 'December';
    break;
  }
}

function duhoc_chart_form_select() {
  $form = array();
  $form['selected'] = array(
    '#type' => 'select',
    '#options' => array(
      '' => 'All',
      0 => t('Hà Nội'),
      1 => t('Hồ Chí Minh'),
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

