<?php
function duhoc_user_init() {
  if(isset($_POST['ajax_html_ids'])) {
    unset($_POST['ajax_html_ids']);
  }
}
/*
 * implement hook_menu
 */

function duhoc_user_menu() {
  $items['user/%/target'] = array(
    'title' => 'Edit targets',
    'page callback' => 'duhoc_user_target',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function duhoc_user_target($uid = '') {
  global $user;
  $uid_login = $user->uid;
  $area = db_query("SELECT field_area_value FROM {field_data_field_area} WHERE entity_id =:uid",array(':uid'=>$uid_login)) ->fetchField();
  $list_uid = db_query("SELECT entity_id FROM {field_data_field_area} WHERE field_area_value = :area",array(':area' =>$area));
  if($list_uid ->rowCount() >0 ) {
    foreach($list_uid as $result) {
      $row[] = $result -> entity_id;
    }
  }
  $uid_view = arg(1);
 if($user ->roles[8]) {
   if(in_array($uid_view,$row)) {
     module_load_include('inc', 'user', 'user.pages');
     $account = user_load($uid);
     $form =  drupal_get_form('user_profile_form', $account);
   }
   if($user->roles[9]) {
     module_load_include('inc', 'user', 'user.pages');
     $account = user_load($uid);
     $form =  drupal_get_form('user_profile_form', $account);
   }
 }
  else
    $form = '<h2 style="text-align: center">Access Denied </h2>';
  return $form;
}

function duhoc_user_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if(!isset($form_state['build_info']['files'])){
    $form_state['build_info']['files'] = array("menu" => "modules/user/user.pages.inc");
  }
  if($form_id == 'user_profile_form') {
    $current_url = arg(2);
    $form['current_url'] = array('#type' => 'hidden', '#value' => $current_url);
    if(isset($form_state['input']['current_url']))
      $m = $form_state['input']['current_url'];
    if(arg(2) == 'target' || (isset($m)&&$m == 'target')) {
      $form['picture']['#access'] = false;
      $form['account']['#access'] = false;
      $form['signature_settings']['#access'] = false;
      $form['fgm_user_user_form_group_targets']['#access'] = true;
      $form['field_area']['#access'] = false;
    }
    if(arg(2) == 'edit' ||(isset($m)&&$m == 'edit')) {
      unset($form['fgm_user_user_form_group_targets']);
      $form['field_area']['#access'] = false;
      if($user -> roles[8])
        $form['field_area']['#access'] = true;
    }
  }
}

/**
 * implement hook block_info
 */

function duhoc_user_block_info() {
  $blocks['user_view'] = array(
    'info' => t('Content user view'),
  );
  return $blocks;
}

/**
 * implement hook_block_view
 */

function duhoc_user_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'user_view':
      $block['content'] = duhoc_user_view();
      break;
  }
  return $block;
}

function duhoc_user_view() {
  global $user;
  if($user ->uid >0) {
  $uid = arg(1);
  $a2 = arg(2);
  $row = array();
  for($i = 1; $i <=12; $i++) {
    $data = duhoc_user_taget($uid,$i);
    $row['month'] = $i;
    $row['target'] = $data['target'];
    if(empty($row['target']))
      $row['target'] = 0;
    $row['revenue'] = $data['revenue'];
    if(empty($row['revenue']))
      $row['revenue'] = 0;
    $rows[]= $row;
  }

  $user1 = user_load($uid,true);
    if(isset($user1->picture->uri))
  $uri = $user1->picture->uri;

  $output = '';
  if(isset($uri))
    $output .= '<div class="user_info"><div class="info_image">'.theme('image_style', array('style_name' => 'user170x170', 'path' => $uri, 'getsize' => TRUE, 'attributes' => array('class' => 'thumb'))).'</div>';
  else
    $output .= '<div class="user_info"><div class="info_image"><img src="http://localhost/duhoc/sites/default/files/no-image.png"> </div>';
  $output .= '<div class="info_name"><span class="label">Name: </span>'.$user1 -> name.'</div>';
  $output .= '<div class="info_area"><span class="label">Area: </span>'.duhoc_user_area($user1 ->field_area['und'][0]['value']).'</div></div>';
  $output .= '<div class="info_targin">'.theme("table",array('header'=>array('Month','Target','Revenue'),'rows' =>$rows )).'</div>';
  if(isset($a2))
    return '';
  else
    return $output;
  }
  else
    return '';
}

function duhoc_user_area($value) {
  $query = db_query("SELECT field_area_user_value FROM {field_data_field_area_user} WHERE delta = :del",array(':del' => $value)) ->fetchField();
  return $query;
}

function duhoc_user_taget($uid,$month) {
  if(isset($uid)) {
    $row = array();
    $query = db_query("SELECT target.field_target_value as tget,  reve.field_revenue_value as rve
                    FROM field_data_field_target as target
                    INNER JOIN field_data_field_th_ng as mont  ON target.entity_id = mont.entity_id
                    INNER JOIN field_data_field_revenue as reve ON mont.entity_id = reve.entity_id
                    WHERE FROM_UNIXTIME(mont.field_th_ng_value,'%c') = ".$month."
                    AND target.entity_id  = ".$uid."
                    AND target.delta = reve.delta
                    AND target.delta = mont.delta
                    ");
    if($query->rowCount() ==0) {
      $row['target']  = 0;
      $row['revenue']  = 0;
    }
    else {
      foreach($query as $result) {
        $row['target']  = $result -> tget;
        $row['revenue']  = $result -> rve;
      }
    }

    return $row;
   }
}
//list danh sach uid de truyen vao views - Phan quyen cho user
function duhoc_user_list() {
  global $user;
  $uid_login = $user->uid;
  if(isset($user->roles[8])) {
    if(isset($user ->roles[9])) {
      $query = db_query("SELECT uid FROM {users} WHERE uid >0");
      foreach($query as $result){
        $row[] = $result -> uid;
      }
      $list_uid = implode('+',$row);
    }
   else {
     $area = db_query("SELECT field_area_value FROM {field_data_field_area} WHERE entity_id =:uid",array(':uid'=>$uid_login)) ->fetchField();
     $query = db_query("SELECT entity_id FROM {field_data_field_area} WHERE field_area_value = :area",array(':area' =>$area));
     if($query ->rowCount() >0 ) {
       foreach($query as $result) {
         $row[] = $result -> entity_id;
       }
     }
     $list_uid = implode('+',$row);
   }
  }
  else
    $list_uid = $uid_login;

return $list_uid;
}